approvedGitRepositories:
  - "**"

enableGlobalCache: true

npmScopes:
  connor-adams:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmMinimalAgeGate: 0

enableScripts: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 0
