import {
  Model,
  DataTypes,
  Op,
  type Sequelize,
  type ModelAttributes,
  InferAttributes,
  InferCreationAttributes,
  CreationOptional,
} from 'sequelize';

/**
 * Reimbursement claim (issue #216). Tracks money the household expects back
 * for an original outlay `transaction_id` — from a partner, friend, employer,
 * insurer, etc. 1:N with `transactions` (a single outlay can spawn multiple
 * claims), so this model carries its own integer PK rather than reusing
 * `transaction_id` as the PK like the 1:1 sidecars (Purchase,
 * TransactionReturnMetadata).
 *
 * Party is either a structured `contactId` OR free-text `partyName`; routes
 * require at least one. `repaymentTransactionId` links the incoming credit
 * transaction once a repayment is matched.
 *
 * `status` is STRING(16) (not a native enum) so the vocab can grow without a
 * destructive migration. The serializer derives an effective 'overdue' status
 * when status='expected' && dueDate < today, so no cron job is needed; the
 * stored 'overdue' value lets users pin a claim as overdue explicitly.
 */
export type ReimbursementStatus =
  | 'expected'
  | 'received'
  | 'overdue'
  | 'waived';
export const REIMBURSEMENT_STATUSES: readonly ReimbursementStatus[] = [
  'expected',
  'received',
  'overdue',
  'waived',
] as const;

export class Reimbursement extends Model<
  InferAttributes<Reimbursement>,
  InferCreationAttributes<Reimbursement>
> {
  declare id: CreationOptional<number>;
  declare householdId: number;
  /**
   * The outlay this claim expects back. Null ONLY for `kind='interest'` rows:
   * allocated line-of-credit interest is owed for a *period*, not for a single
   * outlay, and pointing at an arbitrary loan row would invent provenance.
   */
  declare transactionId: number | null;
  /** Structured party (Contact in same household); null when free-text. */
  declare contactId: number | null;
  /** Free-text party label; null when a Contact is referenced. */
  declare partyName: string | null;
  /** DECIMAL(14,4) returned as a string by sequelize. */
  declare amount: string;
  declare currency: string;
  /** YYYY-MM-DD (DATEONLY); null when no due date set. */
  declare dueDate: string | null;
  declare status: CreationOptional<ReimbursementStatus>;
  /** The incoming credit transaction once a repayment is matched. */
  declare repaymentTransactionId: number | null;
  /** Set when the claim is marked received. */
  declare receivedAt: Date | null;
  declare createdByUserId: number | null;
  declare notes: string | null;
  /** True when this claim was generated by the multiway split action. */
  declare fromSplit: CreationOptional<boolean>;
  /**
   * `principal` for a hand-logged claim; `interest` for a row the LoC interest
   * allocator derived. Interest rows are generated — never edit them by hand,
   * they are recomputed on the next allocator run.
   */
  declare kind: CreationOptional<string>;
  /** The LOAN INTEREST transaction this interest row was apportioned from. */
  declare sourceTransactionId: CreationOptional<number | null>;
  /**
   * The `account_rate_periods` window this interest row was apportioned from.
   * This — not `sourceTransactionId` — is what the allocator keys on: the rate
   * and the printed Applicable Interest both live on the window, and a statement
   * period can print two windows when prime moves mid-cycle. Null for principal.
   */
  declare sourceRatePeriodId: CreationOptional<number | null>;
  declare readonly createdAt: CreationOptional<Date>;
  declare readonly updatedAt: CreationOptional<Date>;
}

export function initReimbursement(sequelize: Sequelize): typeof Reimbursement {
  Reimbursement.init(
    {
      id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
      householdId: {
        type: DataTypes.INTEGER,
        field: 'household_id',
        allowNull: false,
      },
      transactionId: {
        type: DataTypes.INTEGER,
        field: 'transaction_id',
        allowNull: true,
      },
      contactId: {
        type: DataTypes.INTEGER,
        field: 'contact_id',
        allowNull: true,
      },
      partyName: {
        type: DataTypes.STRING(160),
        field: 'party_name',
        allowNull: true,
      },
      amount: {
        type: DataTypes.DECIMAL(14, 4),
        allowNull: false,
      },
      currency: {
        type: DataTypes.STRING(3),
        allowNull: false,
      },
      dueDate: {
        type: DataTypes.DATEONLY,
        field: 'due_date',
        allowNull: true,
      },
      status: {
        type: DataTypes.STRING(16),
        allowNull: false,
        defaultValue: 'expected',
      },
      repaymentTransactionId: {
        type: DataTypes.INTEGER,
        field: 'repayment_transaction_id',
        allowNull: true,
      },
      receivedAt: {
        type: DataTypes.DATE,
        field: 'received_at',
        allowNull: true,
      },
      createdByUserId: {
        type: DataTypes.INTEGER,
        field: 'created_by_user_id',
        allowNull: true,
      },
      notes: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      fromSplit: {
        type: DataTypes.BOOLEAN,
        field: 'from_split',
        allowNull: false,
        defaultValue: false,
      },
      kind: {
        type: DataTypes.STRING(16),
        allowNull: false,
        defaultValue: 'principal',
      },
      sourceTransactionId: {
        type: DataTypes.INTEGER,
        field: 'source_transaction_id',
        allowNull: true,
      },
      sourceRatePeriodId: {
        type: DataTypes.INTEGER,
        field: 'source_rate_period_id',
        allowNull: true,
      },
    } as ModelAttributes<Reimbursement>,
    {
      sequelize,
      modelName: 'Reimbursement',
      tableName: 'reimbursements',
      underscored: true,
      timestamps: true,
      indexes: [
        {
          unique: true,
          fields: ['source_rate_period_id', 'contact_id'],
          name: 'idx_reimbursements_interest_rate_period',
          where: { source_rate_period_id: { [Op.ne]: null } },
        },
      ],
    },
  );
  return Reimbursement;
}
