/**
 * POST /api/ai/query — natural-language financial query endpoint.
 *
 * The AI is untrusted: it only returns a structured intent JSON; this route
 * delegates to {@link runNaturalLanguageQuery} which validates the intent
 * against a whitelist before running an audited query builder. No raw SQL is
 * ever generated by the model.
 *
 * Mounted in app.ts at `/api/ai` AFTER the existing AI router; Express
 * composes routers in order, so the existing routes continue to work and the
 * `/query` path falls through to this new router.
 */
import { Router } from 'express';
import { aiSuggestLimiter } from './aiRateLimit.js';
import { getOpenAiConfig } from '../config/openai.js';
import { rejectDemoAiRequest } from '../demo/aiAccess.js';
import {
  runNaturalLanguageQuery,
  NlQueryError,
} from '../ai/nlQuery.js';

const router = Router();

router.post('/query', aiSuggestLimiter, async (req, res, next) => {
  try {
    if (rejectDemoAiRequest(req, res)) return;
    if (!getOpenAiConfig()) {
      res
        .status(503)
        .json({ error: 'AI features are not configured (set OPENAI_API_KEY)' });
      return;
    }
    const body = (req.body ?? {}) as { question?: unknown };
    const question = typeof body.question === 'string' ? body.question : '';
    const result = await runNaturalLanguageQuery(req, question);
    res.json({
      question: result.question,
      intent: result.intent,
      answer: result.answer,
      sources: result.sources,
      meta: result.meta,
    });
  } catch (e) {
    if (e instanceof NlQueryError) {
      res.status(e.status).json({ error: e.message, code: e.code });
      return;
    }
    next(e);
  }
});

export default router;
