// shared/categoryIcons.ts
//
// Names MUST exactly match lucide-react exports. Keep this list curated —
// every name listed here is imported into the frontend bundle.

export const CATEGORY_ICON_NAMES = [
  'ShoppingCart',
  'ShoppingBag',
  'Utensils',
  'Coffee',
  'Pizza',
  'Beer',
  'Wine',
  'Home',
  'Bed',
  'Sofa',
  'Lightbulb',
  'Plug',
  'Wifi',
  'Phone',
  'Smartphone',
  'Tv',
  'Laptop',
  'Car',
  'Fuel',
  'Bus',
  'Train',
  'Plane',
  'Bike',
  'ParkingSquare',
  'Stethoscope',
  'Pill',
  'HeartPulse',
  'Dumbbell',
  'GraduationCap',
  'BookOpen',
  'Briefcase',
  'Building2',
  'PiggyBank',
  'Landmark',
  'CreditCard',
  'Banknote',
  'Wallet',
  'Receipt',
  'Gift',
  'PartyPopper',
  'Cake',
  'Baby',
  'PawPrint',
  'Flower2',
  'Trees',
  'Wrench',
  'Hammer',
  'Paintbrush',
  'Scissors',
  'Shirt',
  'Gem',
  'Camera',
  'Music',
  'Film',
  'Gamepad2',
  'Ticket',
  'Map',
  'Mountain',
  'Sun',
  'Cloud',
  'Umbrella',
  'Snowflake',
  'Flame',
  'Droplet',
  'Trash2',
  'Recycle',
  'Leaf',
  'Heart',
  'Star',
  'Sparkles',
  'Tag',
  'Bookmark',
  'Folder',
  'Box',
  'Package',
  'Truck',
  'HandCoins',
  'TrendingUp',
  'TrendingDown',
] as const

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number]

export function isCategoryIconName(value: unknown): value is CategoryIconName {
  return (
    typeof value === 'string' &&
    (CATEGORY_ICON_NAMES as readonly string[]).includes(value)
  )
}
