import { safePct, safeNum, clampPct } from './num'
describe('safePct', () => {
  it('finite value', () => expect(safePct(50)).toBe('50.0%'))
  it('clamped above 100', () => expect(safePct(105)).toBe('100.0%'))
  it('clamped below 0', () => expect(safePct(-3)).toBe('0.0%'))
  it('real zero', () => expect(safePct(0)).toBe('0.0%'))
  it('NaN fallback', () => expect(safePct(NaN)).toBe('—'))
  it('Infinity fallback', () => expect(safePct(Infinity)).toBe('—'))
  it('-Infinity fallback', () => expect(safePct(-Infinity)).toBe('—'))
  it('null fallback', () => expect(safePct(null)).toBe('—'))
  it('undefined fallback', () => expect(safePct(undefined)).toBe('—'))
  it('custom fallback', () => expect(safePct(NaN, { fallback: 'N/A' })).toBe('N/A'))
  it('custom digits', () => expect(safePct(50, { digits: 0 })).toBe('50%'))
  it('no clamp', () => expect(safePct(105, { clamp: false })).toBe('105.0%'))
})
describe('safeNum', () => {
  it('finite', () => expect(safeNum(42)).toBe(42))
  it('NaN → null', () => expect(safeNum(NaN)).toBeNull())
  it('Infinity → null', () => expect(safeNum(Infinity)).toBeNull())
  it('-Infinity → null', () => expect(safeNum(-Infinity)).toBeNull())
  it('null → null', () => expect(safeNum(null)).toBeNull())
  it('undefined → null', () => expect(safeNum(undefined)).toBeNull())
  it('string number', () => expect(safeNum('3.14')).toBe(3.14))
})
describe('clampPct', () => {
  it('in range', () => expect(clampPct(50)).toBe(50))
  it('above 100', () => expect(clampPct(105)).toBe(100))
  it('below 0', () => expect(clampPct(-3)).toBe(0))
  it('NaN → 0', () => expect(clampPct(NaN)).toBe(0))
  it('Infinity → 100', () => expect(clampPct(Infinity)).toBe(100))
  it('-Infinity → 0', () => expect(clampPct(-Infinity)).toBe(0))
})
